FROM python
RUN apt-get update -y && \  
   apt-get install -y python3-pip python-dev
RUN pip3 install flask
WORKDIR /app
VOLUME /app
EXPOSE ${API_PORT}
CMD ["python", "api.py"]

#Solve port 5000 alreadt being in use
#https://twissmueller.medium.com/resolving-the-problem-of-port-5000-already-being-in-use-dd2fe4bad0be