FROM dpage/pgadmin4
ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=pass
EXPOSE 80 

# docker run --name mydba --network mynetwork  -p 8081:80 -d week3
#docker network create mynetwork        
# docker run -e PGADMIN_DEFAULT_EMAIL=... dpage/pgadmin4