FROM python
RUN apt-get update -y && \  
   apt-get install -y python3-pip python-dev
RUN pip3 install flask
RUN pip3 install requests


VOLUME ["/app"]
WORKDIR /app

EXPOSE ${CONSUMER_PORT}

CMD ["python", "consumer.py"]